/*
 * Datos del Calendario institucional — Universidad de Cundinamarca.
 *
 * Este es el único archivo que hay que editar para publicar actividades.
 * Los catálogos y las actividades de abajo son DATOS DE EJEMPLO del diseño:
 * reemplázalos por los oficiales.
 *
 * Campos de cada actividad:
 *   nombre       Texto que se muestra en el calendario.
 *   tipo         Una de las claves de "tipos" (define el color).
 *   inicio, fin  Fechas en formato AAAA-MM-DD. Si dura un solo día, repite la fecha.
 *   hora         "HH:MM" en formato 24 h, o '' si es de todo el día.
 *   responsable  Uno de los nombres de "responsables".
 *   lider        Una de las "unidadesLider".
 *   regionales   'todas', o una lista con nombres de "unidadesRegionales".
 *   documento    Nombre del documento de soporte ('' si no hay).
 *   enlace       URL del documento; si está vacío no se muestra el botón "Abrir".
 *   estado       Opcional. Solo para fijar 'Aplazada' (u otro estado) a mano;
 *                si se omite se calcula solo: Programada, En curso o Finalizada.
 */
window.CALENDARIO = {
  subtitulo: 'Universidad de Cundinamarca · 2026',

  // Colorear las actividades según su tipo (false = todas en gris).
  colorPorTipo: true,

  unidadesRegionales: [
    'Fusagasugá',
    'Girardot',
    'Ubaté',
    'Chía',
    'Chocontá',
    'Facatativá',
    'Soacha',
    'Zipaquirá',
    'Bogotá D.C.'
  ],

  unidadesLider: [
    'Vicerrectoría Académica',
    'Vicerrectoría Administrativa y Financiera',
    'Dirección de Planeación Institucional',
    'Dirección de Investigación',
    'Bienestar Universitario',
    'Admisiones y Registro',
    'Interacción Social Universitaria',
    'Autoevaluación y Acreditación'
  ],

  responsables: [
    'María Fernanda Rojas',
    'Carlos Andrés Peña',
    'Luisa Moreno Díaz',
    'Jorge Iván Castillo',
    'Diana Marcela Ruiz',
    'Andrés Felipe Gómez',
    'Paula Andrea Vargas',
    'Ricardo Salazar Ortiz'
  ],

  tipos: {
    'Académica': { solid: '#007B3E', bg: '#dcefe4', fg: '#00482B' },
    'Administrativa': { solid: '#DAAA00', bg: '#fdf3c2', fg: '#5c4700' },
    'Evento': { solid: '#00A99D', bg: '#d6f1ee', fg: '#00564f' },
    'Convocatoria': { solid: '#F7931E', bg: '#fde6cc', fg: '#7a4300' },
    'Institucional': { solid: '#79C000', bg: '#e7f4d0', fg: '#3a5c00' }
  },

  actividades: [
    { nombre: 'Inicio de clases 2026-II', tipo: 'Académica',
      inicio: '2026-08-03', fin: '2026-08-03', hora: '07:00',
      responsable: 'Luisa Moreno Díaz', lider: 'Vicerrectoría Académica',
      regionales: 'todas',
      documento: 'Acuerdo calendario académico 2026-II.pdf', enlace: '' },
    { nombre: 'Ajustes de matrícula académica', tipo: 'Administrativa',
      inicio: '2026-08-03', fin: '2026-08-14', hora: '',
      responsable: 'Diana Marcela Ruiz', lider: 'Admisiones y Registro',
      regionales: 'todas',
      documento: 'Circular informativa.pdf', enlace: '' },
    { nombre: 'Primer corte de notas (30 %)', tipo: 'Académica',
      inicio: '2026-09-07', fin: '2026-09-12', hora: '',
      responsable: 'Luisa Moreno Díaz', lider: 'Vicerrectoría Académica',
      regionales: 'todas',
      documento: 'Acuerdo calendario académico 2026-II.pdf', enlace: '' },
    { nombre: 'Convocatoria interna de proyectos de investigación', tipo: 'Convocatoria',
      inicio: '2026-09-01', fin: '2026-10-09', hora: '',
      responsable: 'Jorge Iván Castillo', lider: 'Dirección de Investigación',
      regionales: 'todas',
      documento: 'Términos de referencia.pdf', enlace: '' },
    { nombre: 'Capacitación en el Sistema Integrado de Gestión', tipo: 'Administrativa',
      inicio: '2026-09-10', fin: '2026-09-10', hora: '08:00',
      responsable: 'Carlos Andrés Peña', lider: 'Dirección de Planeación Institucional',
      regionales: ['Bogotá D.C.'],
      documento: 'Circular informativa.pdf', enlace: '' },
    { nombre: 'Comité de Planeación Institucional', tipo: 'Institucional',
      inicio: '2026-09-25', fin: '2026-09-25', hora: '10:00',
      responsable: 'Carlos Andrés Peña', lider: 'Dirección de Planeación Institucional',
      regionales: ['Fusagasugá'],
      documento: 'Agenda y orden del día.pdf', enlace: '' },
    { nombre: 'Jornada de salud y bienestar', tipo: 'Evento',
      inicio: '2026-09-22', fin: '2026-09-24', hora: '08:00',
      responsable: 'Paula Andrea Vargas', lider: 'Bienestar Universitario',
      regionales: ['Girardot'],
      documento: 'Programación del evento.pdf', enlace: '' },
    { nombre: 'Visita de pares académicos · Ingeniería de Sistemas', tipo: 'Institucional',
      inicio: '2026-09-28', fin: '2026-09-30', hora: '08:00',
      responsable: 'Ricardo Salazar Ortiz', lider: 'Autoevaluación y Acreditación',
      regionales: ['Facatativá'],
      documento: 'Agenda y orden del día.pdf', enlace: '' },
    { nombre: 'Cierre presupuestal del trimestre', tipo: 'Administrativa',
      inicio: '2026-09-30', fin: '2026-09-30', hora: '',
      responsable: 'María Fernanda Rojas', lider: 'Vicerrectoría Administrativa y Financiera',
      regionales: 'todas',
      documento: 'Circular informativa.pdf', enlace: '' },
    { nombre: 'Feria de emprendimiento', tipo: 'Evento',
      inicio: '2026-10-01', fin: '2026-10-02', hora: '09:00',
      responsable: 'Andrés Felipe Gómez', lider: 'Interacción Social Universitaria',
      regionales: ['Soacha'],
      documento: 'Programación del evento.pdf', enlace: '' },
    { nombre: 'Solicitud de exámenes supletorios', tipo: 'Académica',
      inicio: '2026-09-14', fin: '2026-09-18', hora: '',
      responsable: 'Diana Marcela Ruiz', lider: 'Admisiones y Registro',
      regionales: 'todas',
      documento: 'Acuerdo calendario académico 2026-II.pdf', enlace: '' },
    { nombre: 'Semana de receso estudiantil', tipo: 'Académica',
      inicio: '2026-10-05', fin: '2026-10-09', hora: '',
      responsable: 'Luisa Moreno Díaz', lider: 'Vicerrectoría Académica',
      regionales: 'todas',
      documento: 'Acuerdo calendario académico 2026-II.pdf', enlace: '' },
    { nombre: 'Encuentro regional de semilleros de investigación', tipo: 'Evento',
      inicio: '2026-10-14', fin: '2026-10-16', hora: '08:00',
      responsable: 'Jorge Iván Castillo', lider: 'Dirección de Investigación',
      regionales: ['Zipaquirá', 'Chía'],
      documento: 'Programación del evento.pdf', enlace: '' },
    { nombre: 'Segundo corte de notas (30 %)', tipo: 'Académica',
      inicio: '2026-10-19', fin: '2026-10-24', hora: '',
      responsable: 'Luisa Moreno Díaz', lider: 'Vicerrectoría Académica',
      regionales: 'todas',
      documento: 'Acuerdo calendario académico 2026-II.pdf', enlace: '' },
    { nombre: 'Audiencia pública de rendición de cuentas', tipo: 'Institucional',
      inicio: '2026-10-29', fin: '2026-10-29', hora: '09:00',
      responsable: 'Carlos Andrés Peña', lider: 'Dirección de Planeación Institucional',
      regionales: ['Fusagasugá'],
      documento: 'Agenda y orden del día.pdf', enlace: '' },
    { nombre: 'Inscripciones de aspirantes 2027-I', tipo: 'Convocatoria',
      inicio: '2026-09-15', fin: '2026-11-13', hora: '',
      responsable: 'Diana Marcela Ruiz', lider: 'Admisiones y Registro',
      regionales: 'todas',
      documento: 'Términos de referencia.pdf', enlace: '' },
    { nombre: 'Evaluación docente', tipo: 'Académica',
      inicio: '2026-11-03', fin: '2026-11-20', hora: '',
      responsable: 'Luisa Moreno Díaz', lider: 'Vicerrectoría Académica',
      regionales: 'todas',
      documento: 'Acuerdo calendario académico 2026-II.pdf', enlace: '' },
    { nombre: 'Ajuste al plan anual de adquisiciones', tipo: 'Administrativa',
      inicio: '2026-10-13', fin: '2026-10-13', hora: '14:00',
      responsable: 'María Fernanda Rojas', lider: 'Vicerrectoría Administrativa y Financiera',
      regionales: ['Fusagasugá'],
      documento: 'Circular informativa.pdf', enlace: '', estado: 'Aplazada' },
    { nombre: 'Mantenimiento de la plataforma académica', tipo: 'Administrativa',
      inicio: '2026-09-26', fin: '2026-09-27', hora: '',
      responsable: 'María Fernanda Rojas', lider: 'Vicerrectoría Administrativa y Financiera',
      regionales: 'todas',
      documento: 'Circular informativa.pdf', enlace: '' },
    { nombre: 'Taller de autoevaluación de programas', tipo: 'Institucional',
      inicio: '2026-09-16', fin: '2026-09-16', hora: '14:00',
      responsable: 'Ricardo Salazar Ortiz', lider: 'Autoevaluación y Acreditación',
      regionales: ['Ubaté'],
      documento: 'Agenda y orden del día.pdf', enlace: '' },
    { nombre: 'Torneo deportivo interunidades', tipo: 'Evento',
      inicio: '2026-10-20', fin: '2026-10-23', hora: '',
      responsable: 'Paula Andrea Vargas', lider: 'Bienestar Universitario',
      regionales: ['Chocontá', 'Ubaté'],
      documento: 'Programación del evento.pdf', enlace: '' },
    { nombre: 'Brigada de extensión rural', tipo: 'Evento',
      inicio: '2026-09-19', fin: '2026-09-19', hora: '07:30',
      responsable: 'Andrés Felipe Gómez', lider: 'Interacción Social Universitaria',
      regionales: ['Chocontá'],
      documento: 'Programación del evento.pdf', enlace: '' },
    { nombre: 'Consejo Académico · sesión ordinaria', tipo: 'Institucional',
      inicio: '2026-09-29', fin: '2026-09-29', hora: '14:00',
      responsable: 'Luisa Moreno Díaz', lider: 'Vicerrectoría Académica',
      regionales: ['Fusagasugá'],
      documento: 'Agenda y orden del día.pdf', enlace: '' },
    { nombre: 'Pago de matrícula ordinaria 2027-I', tipo: 'Administrativa',
      inicio: '2026-11-23', fin: '2026-12-04', hora: '',
      responsable: 'María Fernanda Rojas', lider: 'Vicerrectoría Administrativa y Financiera',
      regionales: 'todas',
      documento: 'Circular informativa.pdf', enlace: '' },
    { nombre: 'Exámenes finales', tipo: 'Académica',
      inicio: '2026-11-23', fin: '2026-11-28', hora: '',
      responsable: 'Luisa Moreno Díaz', lider: 'Vicerrectoría Académica',
      regionales: 'todas',
      documento: 'Acuerdo calendario académico 2026-II.pdf', enlace: '' },
    { nombre: 'Convocatoria de movilidad académica', tipo: 'Convocatoria',
      inicio: '2026-09-08', fin: '2026-10-02', hora: '',
      responsable: 'Andrés Felipe Gómez', lider: 'Interacción Social Universitaria',
      regionales: 'todas',
      documento: 'Términos de referencia.pdf', enlace: '' },
    { nombre: 'Semana de la ciencia y la innovación', tipo: 'Evento',
      inicio: '2026-11-09', fin: '2026-11-13', hora: '',
      responsable: 'Jorge Iván Castillo', lider: 'Dirección de Investigación',
      regionales: ['Girardot', 'Fusagasugá'],
      documento: 'Programación del evento.pdf', enlace: '' },
    { nombre: 'Ceremonia de grados', tipo: 'Institucional',
      inicio: '2026-12-11', fin: '2026-12-11', hora: '10:00',
      responsable: 'Diana Marcela Ruiz', lider: 'Admisiones y Registro',
      regionales: ['Fusagasugá'],
      documento: 'Agenda y orden del día.pdf', enlace: '' },
    { nombre: 'Auditoría interna de calidad', tipo: 'Institucional',
      inicio: '2026-10-26', fin: '2026-10-28', hora: '',
      responsable: 'Carlos Andrés Peña', lider: 'Dirección de Planeación Institucional',
      regionales: ['Facatativá', 'Soacha'],
      documento: 'Agenda y orden del día.pdf', enlace: '', estado: 'Aplazada' },
    { nombre: 'Cierre del semestre 2026-II', tipo: 'Académica',
      inicio: '2026-12-05', fin: '2026-12-05', hora: '',
      responsable: 'Luisa Moreno Díaz', lider: 'Vicerrectoría Académica',
      regionales: 'todas',
      documento: 'Acuerdo calendario académico 2026-II.pdf', enlace: '' },
    { nombre: 'Inducción a docentes nuevos', tipo: 'Académica',
      inicio: '2026-09-24', fin: '2026-09-24', hora: '08:00',
      responsable: 'Luisa Moreno Díaz', lider: 'Vicerrectoría Académica',
      regionales: ['Chía', 'Zipaquirá'],
      documento: 'Acuerdo calendario académico 2026-II.pdf', enlace: '' },
    { nombre: 'Convocatoria de monitorías académicas', tipo: 'Convocatoria',
      inicio: '2026-09-21', fin: '2026-09-30', hora: '',
      responsable: 'Paula Andrea Vargas', lider: 'Bienestar Universitario',
      regionales: 'todas',
      documento: 'Términos de referencia.pdf', enlace: '' }
  ]
};
