/**
 * Actividades del calendario. DATOS DE EJEMPLO del diseño: reemplázalos por los oficiales.
 *
 * Campos:
 *   nombre       Texto que se muestra en el calendario.
 *   tipo         Una clave de `tiposActividad` (define el color).
 *   inicio, fin  AAAA-MM-DD. Si dura un día, repite la fecha.
 *   hora         Opcional, "HH:MM" en 24 h. Sin hora = todo el día.
 *   responsable  Un nombre de `responsables`.
 *   lider        Una de `unidadesLider`.
 *   regionales   'todas' o una lista de `unidadesRegionales`.
 *   documento    Opcional, nombre del documento de soporte.
 *   enlace       Opcional, URL del documento; sin enlace no se muestra "Abrir".
 *   estado       Opcional, solo para fijarlo a mano (p. ej. 'Aplazada'). Si se omite
 *                se calcula: Programada, En curso o Finalizada.
 */
import type { ActividadFuente } from '@/features/calendario/tipos';

export const actividades: ActividadFuente[] = [
  {
    nombre: 'Inicio de clases 2026-II',
    tipo: 'Académica',
    inicio: '2026-08-03',
    fin: '2026-08-03',
    hora: '07:00',
    responsable: 'Luisa Moreno Díaz',
    lider: 'Vicerrectoría Académica',
    regionales: 'todas',
    documento: 'Acuerdo calendario académico 2026-II.pdf',
  },
  {
    nombre: 'Ajustes de matrícula académica',
    tipo: 'Administrativa',
    inicio: '2026-08-03',
    fin: '2026-08-14',
    responsable: 'Diana Marcela Ruiz',
    lider: 'Admisiones y Registro',
    regionales: 'todas',
    documento: 'Circular informativa.pdf',
  },
  {
    nombre: 'Primer corte de notas (30 %)',
    tipo: 'Académica',
    inicio: '2026-09-07',
    fin: '2026-09-12',
    responsable: 'Luisa Moreno Díaz',
    lider: 'Vicerrectoría Académica',
    regionales: 'todas',
    documento: 'Acuerdo calendario académico 2026-II.pdf',
  },
  {
    nombre: 'Convocatoria interna de proyectos de investigación',
    tipo: 'Convocatoria',
    inicio: '2026-09-01',
    fin: '2026-10-09',
    responsable: 'Jorge Iván Castillo',
    lider: 'Dirección de Investigación',
    regionales: 'todas',
    documento: 'Términos de referencia.pdf',
  },
  {
    nombre: 'Capacitación en el Sistema Integrado de Gestión',
    tipo: 'Administrativa',
    inicio: '2026-09-10',
    fin: '2026-09-10',
    hora: '08:00',
    responsable: 'Carlos Andrés Peña',
    lider: 'Dirección de Planeación Institucional',
    regionales: ['Bogotá D.C.'],
    documento: 'Circular informativa.pdf',
  },
  {
    nombre: 'Comité de Planeación Institucional',
    tipo: 'Institucional',
    inicio: '2026-09-25',
    fin: '2026-09-25',
    hora: '10:00',
    responsable: 'Carlos Andrés Peña',
    lider: 'Dirección de Planeación Institucional',
    regionales: ['Fusagasugá'],
    documento: 'Agenda y orden del día.pdf',
  },
  {
    nombre: 'Jornada de salud y bienestar',
    tipo: 'Evento',
    inicio: '2026-09-22',
    fin: '2026-09-24',
    hora: '08:00',
    responsable: 'Paula Andrea Vargas',
    lider: 'Bienestar Universitario',
    regionales: ['Girardot'],
    documento: 'Programación del evento.pdf',
  },
  {
    nombre: 'Visita de pares académicos · Ingeniería de Sistemas',
    tipo: 'Institucional',
    inicio: '2026-09-28',
    fin: '2026-09-30',
    hora: '08:00',
    responsable: 'Ricardo Salazar Ortiz',
    lider: 'Autoevaluación y Acreditación',
    regionales: ['Facatativá'],
    documento: 'Agenda y orden del día.pdf',
  },
  {
    nombre: 'Cierre presupuestal del trimestre',
    tipo: 'Administrativa',
    inicio: '2026-09-30',
    fin: '2026-09-30',
    responsable: 'María Fernanda Rojas',
    lider: 'Vicerrectoría Administrativa y Financiera',
    regionales: 'todas',
    documento: 'Circular informativa.pdf',
  },
  {
    nombre: 'Feria de emprendimiento',
    tipo: 'Evento',
    inicio: '2026-10-01',
    fin: '2026-10-02',
    hora: '09:00',
    responsable: 'Andrés Felipe Gómez',
    lider: 'Interacción Social Universitaria',
    regionales: ['Soacha'],
    documento: 'Programación del evento.pdf',
  },
  {
    nombre: 'Solicitud de exámenes supletorios',
    tipo: 'Académica',
    inicio: '2026-09-14',
    fin: '2026-09-18',
    responsable: 'Diana Marcela Ruiz',
    lider: 'Admisiones y Registro',
    regionales: 'todas',
    documento: 'Acuerdo calendario académico 2026-II.pdf',
  },
  {
    nombre: 'Semana de receso estudiantil',
    tipo: 'Académica',
    inicio: '2026-10-05',
    fin: '2026-10-09',
    responsable: 'Luisa Moreno Díaz',
    lider: 'Vicerrectoría Académica',
    regionales: 'todas',
    documento: 'Acuerdo calendario académico 2026-II.pdf',
  },
  {
    nombre: 'Encuentro regional de semilleros de investigación',
    tipo: 'Evento',
    inicio: '2026-10-14',
    fin: '2026-10-16',
    hora: '08:00',
    responsable: 'Jorge Iván Castillo',
    lider: 'Dirección de Investigación',
    regionales: ['Zipaquirá', 'Chía'],
    documento: 'Programación del evento.pdf',
  },
  {
    nombre: 'Segundo corte de notas (30 %)',
    tipo: 'Académica',
    inicio: '2026-10-19',
    fin: '2026-10-24',
    responsable: 'Luisa Moreno Díaz',
    lider: 'Vicerrectoría Académica',
    regionales: 'todas',
    documento: 'Acuerdo calendario académico 2026-II.pdf',
  },
  {
    nombre: 'Audiencia pública de rendición de cuentas',
    tipo: 'Institucional',
    inicio: '2026-10-29',
    fin: '2026-10-29',
    hora: '09:00',
    responsable: 'Carlos Andrés Peña',
    lider: 'Dirección de Planeación Institucional',
    regionales: ['Fusagasugá'],
    documento: 'Agenda y orden del día.pdf',
  },
  {
    nombre: 'Inscripciones de aspirantes 2027-I',
    tipo: 'Convocatoria',
    inicio: '2026-09-15',
    fin: '2026-11-13',
    responsable: 'Diana Marcela Ruiz',
    lider: 'Admisiones y Registro',
    regionales: 'todas',
    documento: 'Términos de referencia.pdf',
  },
  {
    nombre: 'Evaluación docente',
    tipo: 'Académica',
    inicio: '2026-11-03',
    fin: '2026-11-20',
    responsable: 'Luisa Moreno Díaz',
    lider: 'Vicerrectoría Académica',
    regionales: 'todas',
    documento: 'Acuerdo calendario académico 2026-II.pdf',
  },
  {
    nombre: 'Ajuste al plan anual de adquisiciones',
    tipo: 'Administrativa',
    inicio: '2026-10-13',
    fin: '2026-10-13',
    hora: '14:00',
    responsable: 'María Fernanda Rojas',
    lider: 'Vicerrectoría Administrativa y Financiera',
    regionales: ['Fusagasugá'],
    documento: 'Circular informativa.pdf',
    estado: 'Aplazada',
  },
  {
    nombre: 'Mantenimiento de la plataforma académica',
    tipo: 'Administrativa',
    inicio: '2026-09-26',
    fin: '2026-09-27',
    responsable: 'María Fernanda Rojas',
    lider: 'Vicerrectoría Administrativa y Financiera',
    regionales: 'todas',
    documento: 'Circular informativa.pdf',
  },
  {
    nombre: 'Taller de autoevaluación de programas',
    tipo: 'Institucional',
    inicio: '2026-09-16',
    fin: '2026-09-16',
    hora: '14:00',
    responsable: 'Ricardo Salazar Ortiz',
    lider: 'Autoevaluación y Acreditación',
    regionales: ['Ubaté'],
    documento: 'Agenda y orden del día.pdf',
  },
  {
    nombre: 'Torneo deportivo interunidades',
    tipo: 'Evento',
    inicio: '2026-10-20',
    fin: '2026-10-23',
    responsable: 'Paula Andrea Vargas',
    lider: 'Bienestar Universitario',
    regionales: ['Chocontá', 'Ubaté'],
    documento: 'Programación del evento.pdf',
  },
  {
    nombre: 'Brigada de extensión rural',
    tipo: 'Evento',
    inicio: '2026-09-19',
    fin: '2026-09-19',
    hora: '07:30',
    responsable: 'Andrés Felipe Gómez',
    lider: 'Interacción Social Universitaria',
    regionales: ['Chocontá'],
    documento: 'Programación del evento.pdf',
  },
  {
    nombre: 'Consejo Académico · sesión ordinaria',
    tipo: 'Institucional',
    inicio: '2026-09-29',
    fin: '2026-09-29',
    hora: '14:00',
    responsable: 'Luisa Moreno Díaz',
    lider: 'Vicerrectoría Académica',
    regionales: ['Fusagasugá'],
    documento: 'Agenda y orden del día.pdf',
  },
  {
    nombre: 'Pago de matrícula ordinaria 2027-I',
    tipo: 'Administrativa',
    inicio: '2026-11-23',
    fin: '2026-12-04',
    responsable: 'María Fernanda Rojas',
    lider: 'Vicerrectoría Administrativa y Financiera',
    regionales: 'todas',
    documento: 'Circular informativa.pdf',
  },
  {
    nombre: 'Exámenes finales',
    tipo: 'Académica',
    inicio: '2026-11-23',
    fin: '2026-11-28',
    responsable: 'Luisa Moreno Díaz',
    lider: 'Vicerrectoría Académica',
    regionales: 'todas',
    documento: 'Acuerdo calendario académico 2026-II.pdf',
  },
  {
    nombre: 'Convocatoria de movilidad académica',
    tipo: 'Convocatoria',
    inicio: '2026-09-08',
    fin: '2026-10-02',
    responsable: 'Andrés Felipe Gómez',
    lider: 'Interacción Social Universitaria',
    regionales: 'todas',
    documento: 'Términos de referencia.pdf',
  },
  {
    nombre: 'Semana de la ciencia y la innovación',
    tipo: 'Evento',
    inicio: '2026-11-09',
    fin: '2026-11-13',
    responsable: 'Jorge Iván Castillo',
    lider: 'Dirección de Investigación',
    regionales: ['Girardot', 'Fusagasugá'],
    documento: 'Programación del evento.pdf',
  },
  {
    nombre: 'Ceremonia de grados',
    tipo: 'Institucional',
    inicio: '2026-12-11',
    fin: '2026-12-11',
    hora: '10:00',
    responsable: 'Diana Marcela Ruiz',
    lider: 'Admisiones y Registro',
    regionales: ['Fusagasugá'],
    documento: 'Agenda y orden del día.pdf',
  },
  {
    nombre: 'Auditoría interna de calidad',
    tipo: 'Institucional',
    inicio: '2026-10-26',
    fin: '2026-10-28',
    responsable: 'Carlos Andrés Peña',
    lider: 'Dirección de Planeación Institucional',
    regionales: ['Facatativá', 'Soacha'],
    documento: 'Agenda y orden del día.pdf',
    estado: 'Aplazada',
  },
  {
    nombre: 'Cierre del semestre 2026-II',
    tipo: 'Académica',
    inicio: '2026-12-05',
    fin: '2026-12-05',
    responsable: 'Luisa Moreno Díaz',
    lider: 'Vicerrectoría Académica',
    regionales: 'todas',
    documento: 'Acuerdo calendario académico 2026-II.pdf',
  },
  {
    nombre: 'Inducción a docentes nuevos',
    tipo: 'Académica',
    inicio: '2026-09-24',
    fin: '2026-09-24',
    hora: '08:00',
    responsable: 'Luisa Moreno Díaz',
    lider: 'Vicerrectoría Académica',
    regionales: ['Chía', 'Zipaquirá'],
    documento: 'Acuerdo calendario académico 2026-II.pdf',
  },
  {
    nombre: 'Convocatoria de monitorías académicas',
    tipo: 'Convocatoria',
    inicio: '2026-09-21',
    fin: '2026-09-30',
    responsable: 'Paula Andrea Vargas',
    lider: 'Bienestar Universitario',
    regionales: 'todas',
    documento: 'Términos de referencia.pdf',
  },
];
