/** Dependencias responsables. GENERADO por herramientas/cargar.py desde «data/Calendario institucional.xlsx». */
export const responsables = [
  'Administración de Empresas',
  'Admisiones y Registro',
  'Alata Dirección - Comité SAC Dirección de Planeación coordinadores se los sistemas Integrados de Gestión',
  'Alta Dirección',
  'Alta Dirección - Comité SAC Dirección de Planeación Institucional coordinadores se los sistemas Integrados de Gestión',
  'Alta Dirección Dirección de Planeación Institucional',
  'Atencion al Ciudadano',
  'Atencion al Ciudadano y Control Interno',
  'Bienestar Psicosocial',
  'Bienestar Saludable',
  'Bienestar Universitario',
  'Bienestar Universitario - Chía',
  'Bienestar Universitario - Equidad y Diversidad',
  'Bienestar Universitario - Facatativá',
  'Bienestar Universitario - Fusagasugá',
  'Bienestar Universitario - Girardot',
  'Bienestar Universitario Seccional Girardot',
  'Bienestar Universitario - Soacha',
  'Bienestar Universitario - Ubaté',
  'Bienestar Universitario - Zipaquirá',
  'Bienestar y Admisiones',
  'Contadiría Pública',
  'Contaduría Pública',
  'Coordinación del programa',
  'Coordinación Programa Administración de Empresas',
  'Coordinación Programa Contaduría Pública',
  'Coordinación Programa de Música - dirección Administrativa',
  'Coordinación Programa Ingeniería de Software',
  'Coordinación Programa Ingeniería Industrial',
  'Coordinador de Programa',
  'Coordinador del programa',
  'Coordinadora Sandra Patricia Carmona Urueña',
  'Coordinadora Sandra Patricia Carmona Urueña / Claudia del Rocio Contreras Rodriguez',
  'Coordinadora Sandra Patricia Carmona Urueña y Adriana Marcela Perdomo Martinez',
  'Coordinadora Sandra Patricia Carmona Urueña y Gestores del Conocimiento y el Aprendizaje',
  'Coordinadora Sandra Patricia Carmona Urueña y Marelbi Hidalgo Mejia',
  'Cultura y Deporte',
  'Decana Facultad Maria Nancy Garzon Soche',
  'Decana Facultad Maria Nancy Garzon Soche Coordinadora Sandra Patricia Carmona Urueña',
  'Dirección Administrativa',
  'Dirección Administrativa Apoyo académico y SGA',
  'Dirección Administrativa, Bienestar Universitario, Admisiones, CGCA',
  'Dirección Administrativa Extensión',
  'Dirección Administrativa Programas Académicos y Bienestar Universitario',
  'Dirección Administrativa Programas Académicos y Unidad de Apoyo Académico',
  'Dirección Administrativa y Bienestar Social laboral',
  'Dirección Administrativa y Bienestar Universitario',
  'Dirección Administrativa y Coordinación Programa de Música',
  'Dirección Administrativa y Gestor SGA Ext. Soacha',
  'Dirección Administrativa y Gestor SGA Extensión Soacha',
  'Dirección Administrativa y SGA',
  'Dirección Bienestar Universitario',
  'Dirección Control Interno',
  'Dirección de Bienestar Universitario',
  'Dirección de Interaccion Social Universitaria',
  'Dirección de Planeación',
  'Dirección de Planeacion - Dirección Bienestar Universitario',
  'Dirección de Planeación Directores Administrativos de Seccionales y Extensiones',
  'Dirección de Planeación Institucional',
  'Dirección de Seccional',
  'Dirección de Seccional - Programas Académicos',
  'Dirección de Seccional - Talento Humano Ubaté',
  'Dirección de Talento Humano',
  'Dirección de Talento Humano - Bienestar Social Laboral',
  'Direccion de Talento Humano , Directores de Seccionales y Extensiones.',
  'Dirección de Talento Humano y Dirección de Bienestar Universitario',
  'Dirección Extensión y Talento Humano',
  'Dirección Financiera',
  'Direcciòn Juridica',
  'Dirección Planeación Institucional - Dirección Administrativa',
  'Dirección Sistemas y Tecnologia',
  'Director Administrativo',
  'Director Administrativo y Coordinadora Bienestar Universitario',
  'Director Administrativo y Coordinadores de Programas Académicos',
  'Director Administrativo y Gestor Oficina de Autoevaluación y Acreditación Soacha',
  'Director Administrativo y Gestora área de Compras Extensión Soacha',
  'Director Administrativo y Gestores SIG - Extensión Soacha',
  'Director Adminstrativo Extensión Chia',
  'Director Adminstrativo Extensión Facatativá',
  'Director Adminstrativo Extensión Soacha',
  'Director Adminstrativo Extensión Zipaquirá',
  'Director Adminstrativo Seccional Girardot',
  'Director Adminstrativo Seccional Ubaté',
  'Empresa Externa seleccionada mediante proceso de licitación - Oficina de Archivo y Correspondencia',
  'Equipo CGCA',
  'Facultad de Ciencias Administrativas, Económicas y Contables',
  'Facultad de Ciencias Agropecuarias',
  'Facultad de Ciencias de la Salud',
  'Facultad de Ciencias Sociales, Humanidades y Ciencias Políticas',
  'Facultad de Educación',
  'Facultad de Ingeniería',
  'Gestor Ana Beatriz Melo',
  'gestor Diego Andrés Pava',
  'Gestor Juan Andrés Godoy',
  'Gestor Talento Humano',
  'Gestores área de programación',
  'Gestores de ciencias básicas',
  'Gestores del Conocimiento y el Aprendizaje',
  'Gestores del Conocimiento y el Aprendizaje de X semestre',
  'Gestores del programa - General',
  'Ingeniería de Sistemas y computación',
  'Integrantes del COPASST',
  'Líder CDEI Girardot Luis H Suarez',
  'Líder CDEI Girardot Luis H Suarez Diaz',
  'Líder de Investigación Adriana Roció Rodriguez González',
  'Líder ISU programa de Administración de Empresas',
  'Medicina Veterinaria',
  'No registrado',
  'Oficina asesora de comunicaciones',
  'Oficina de Admisiones y Registro',
  'Oficina de Archivo y Correspondencia',
  'Oficina de Archivo y Correspondencia - Dirección de Sistemas y Tecnología -Sistema de Seguridad de la Información',
  'Oficina de Archivo y Correspondencia - Dirección de Sistemas y Tecnología - Sistema de Seguridad de la Información - Software Documental (proveedor)',
  'Oficina de Archivo y Correspondencia - Seccional Ubaté - Seccional Girardot -Extensión Soacha - Extensión Zipaquirá - Extensión Chía - Extensión Facatativá',
  'Oficina de Calidad. * Oficina de Archivo y Correspondencia',
  'Oficina de Compras',
  'Oficina de Contabilidad',
  'Oficina de Graduados',
  'Oficina de Presupuesto',
  'Oficina de Recursos Físicos',
  'Oficina de Seguridad y Salud en el Trabajo',
  'Oficina SST',
  'Oficina Talento Humano',
  'Profesional Ambiental SGA - Girardot',
  'Programa Administración',
  'Programa Administración de Empresas',
  'Programa Contaduria Pública',
  'Programa de Administración de Empresas',
  'Programa de Ciencias del Deporte y la Educación Fisica',
  'Programa de Contaduria Publica',
  'Programa de Enfermeria',
  'Programa de Ingenieria Agronomica',
  'Programa de Ingenieria Ambiental',
  'Programa de Ingenieria de sistemas',
  'Programa de Licencitura en Educación Fisica',
  'Programa de música',
  'Programa de Psicologia',
  'Programa Ingenieria de Sistemas',
  'Programa Ingenieria de Sistemas y Computación',
  'Programa Ingenieria de Software',
  'Programa Ingenieria Electronica',
  'Programa Ingenieria Industrial',
  'Programa Zootecnia',
  'Programas Académicos',
  'Programas Industrial/Sistemas/Mecatrónica',
  'Secretaria General',
  'Secretaría Tecnica del Comité Talento Humano',
  'Seguridad y Salud en el Trabajo',
  'SG-Ambiental',
  'Sistema de Gestión ambiental',
  'Sistema de Gestión de Seguridad de la Información - SGSI',
  'Sistema Gestión Calidad – SGC',
  'Sistemas Integrados',
  'Talento Humano- Bienestar Universitario',
  'Tecnologia en Desarrollo de Software',
  'Vicerrectoría Académica',
  'Vicerrectoría Administrativa y Financiera',
  'Vicerrectoría Administrativa y Financiera, Dirección de Bienestar Universitario, Seccionales y Extensiones',
  'Zootecnia',
] as const;
